### ISSUE TITLE
Missing development dependency

### ISSUE THREAD

**Issue by julianolf** [noverde/faster-sam#208]
When attempting to execute the tests for this package, the following errors occurred:

```
(.venv) juliano@rama faster-sam % make test
coverage run --source=faster_sam -m unittest -b
...............................................................EE...................
======================================================================
ERROR: tests.test_middleware_queue_path_rewriter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_middleware_queue_path_rewriter
Traceback (most recent call last):
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/starlette/testclient.py", line 33, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliano/.pyenv/versions/3.8.18/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/juliano/.pyenv/versions/3.8.18/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/juliano/github/julianolf/faster-sam/tests/test_middleware_queue_path_rewriter.py", line 5, in <module>
    from fastapi.testclient import TestClient
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/fastapi/testclient.py", line 1, in <module>
    from starlette.testclient import TestClient as TestClient  # noqa
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/starlette/testclient.py", line 35, in <module>
    raise RuntimeError(
RuntimeError: The starlette.testclient module requires the httpx package to be installed.
You can install this with:
    $ pip install httpx



======================================================================
ERROR: tests.test_middleware_remove_path (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_middleware_remove_path
Traceback (most recent call last):
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/starlette/testclient.py", line 33, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliano/.pyenv/versions/3.8.18/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/juliano/.pyenv/versions/3.8.18/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/juliano/github/julianolf/faster-sam/tests/test_middleware_remove_path.py", line 7, in <module>
    from fastapi.testclient import TestClient
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/fastapi/testclient.py", line 1, in <module>
    from starlette.testclient import TestClient as TestClient  # noqa
  File "/Users/juliano/github/julianolf/faster-sam/.venv/lib/python3.8/site-packages/starlette/testclient.py", line 35, in <module>
    raise RuntimeError(
RuntimeError: The starlette.testclient module requires the httpx package to be installed.
You can install this with:
    $ pip install httpx



----------------------------------------------------------------------
Ran 84 tests in 0.590s

FAILED (errors=2)
make: *** [test] Error 1
```

The `httpx` package is required by TestClient from FastAPI and should be installed as a development dependency.

**Comment by julianolf** [comment]
It seems it was a problem with old version of FastAPI where httpx was not a direct dependency, not it is installed automatically.
